# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-11 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('real_name', models.TextField(max_length=256)),
                ('affiliation', models.TextField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('difficulty', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField()),
                ('shield', models.PositiveIntegerField()),
                ('armour', models.PositiveIntegerField()),
                ('role', models.TextField(max_length=100)),
                ('occupation', models.TextField(max_length=100)),
                ('favourite_quote', models.TextField(max_length=256)),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='HeroAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cooldown', models.TextField(max_length=100)),
                ('image', models.URLField()),
                ('damage', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=100)),
                ('healing', models.TextField(max_length=100)),
                ('casting_time', models.TextField(max_length=100)),
                ('movement_speed', models.TextField(max_length=100)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='heroes.Hero')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='HeroUltimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aim_type', models.TextField(max_length=100)),
                ('cost', models.TextField(max_length=100)),
                ('casting_time', models.TextField(max_length=100)),
                ('movement_speed', models.TextField(max_length=100)),
                ('duration', models.FloatField()),
                ('damage', models.TextField(max_length=100)),
                ('healing', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='HeroWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('weapon_type', models.TextField(max_length=100)),
                ('aim_type', models.TextField(max_length=100)),
                ('damage', models.TextField(max_length=100)),
                ('movement_speed', models.TextField(max_length=100)),
                ('rate_of_fire', models.TextField(max_length=100)),
                ('ammo', models.TextField(max_length=100)),
                ('headshot', models.TextField(max_length=100)),
                ('spread', models.TextField(max_length=100)),
                ('falloff_range', models.TextField(max_length=100)),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='ultimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_ultimate', to='heroes.HeroUltimate'),
        ),
        migrations.AddField(
            model_name='hero',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_weapon', to='heroes.HeroWeapon'),
        ),
    ]
