# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-11 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='ultimate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_ultimate', to='heroes.HeroUltimate'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_weapon', to='heroes.HeroWeapon'),
        ),
    ]
