# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_auto_20200911_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='abilites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_ability', to='heroes.HeroAbility'),
        ),
    ]
