# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_hero_abilites'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroweapon',
            name='max_range',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='ammo',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='falloff_range',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='headshot',
            field=models.TextField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='movement_speed',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='rate_of_fire',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, default=None, editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='spread',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
