# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_auto_20200911_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='armour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='favourite_quote',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='occupation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='real_name',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='shield',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
