# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-11 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_auto_20200911_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
