# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0007_auto_20200911_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroability',
            name='casting_time',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='damage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='healing',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='movement_speed',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroultimate',
            name='aim_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroultimate',
            name='casting_time',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroultimate',
            name='damage',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroultimate',
            name='healing',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroultimate',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroultimate',
            name='movement_speed',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='ammo',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='falloff_range',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='headshot',
            field=models.TextField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='max_range',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='movement_speed',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='rate_of_fire',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='spread',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='weapon_type',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
