# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_remove_hero_abilites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='ultimate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ultimate', to='heroes.HeroUltimate'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='heroes.HeroWeapon'),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abilities', to='heroes.Hero'),
        ),
        migrations.AlterField(
            model_name='heroability',
            name='image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
