# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0010_auto_20200912_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroability',
            name='preview_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
