# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0011_heroability_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroability',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='hero',
            name='preview_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
