# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0012_auto_20200912_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='affiliation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
