# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-13 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0014_auto_20200913_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroweapon',
            name='weapon_type',
        ),
        migrations.AddField(
            model_name='heroweapon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='aim_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='ammo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='damage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='falloff_range',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='headshot',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='max_range',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='movement_speed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='rate_of_fire',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroweapon',
            name='spread',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
