# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-13 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0020_auto_20200913_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroweapon',
            name='area_of_effect',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
