# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-13 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0021_heroweapon_area_of_effect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Heroes'},
        ),
        migrations.AlterModelOptions(
            name='heroability',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'Hero Abilites'},
        ),
        migrations.AlterModelOptions(
            name='heroultimate',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'Hero Ultimates'},
        ),
        migrations.AlterModelOptions(
            name='heroweapon',
            options={'ordering': ('-pk',), 'verbose_name_plural': 'Hero Weapons'},
        ),
        migrations.AlterField(
            model_name='heroability',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
