# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0024_heroability_area_of_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroability',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
