# Generated by Django 2.2.16 on 2020-09-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0026_heroability_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='sound',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
