# Generated by Django 2.2.16 on 2020-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0027_hero_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
